# Generated by Django 2.2.6 on 2022-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20220328_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_instructions',
            field=models.TextField(null=True),
        ),
    ]
